# Generated by Django 4.1.1 on 2022-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vessel",
            name="lat",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vessel",
            name="lng",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
