# Generated by Django 4.1.1 on 2022-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_vessel_address_vessel_lat_vessel_lng_alter_vessel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="lng",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
    ]
