# Generated by Django 4.1.1 on 2022-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_vessel_lat_alter_vessel_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="lng",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
    ]
