# Generated by Django 4.1.1 on 2022-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_vessel_lat_alter_vessel_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="lat",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="lng",
            field=models.FloatField(blank=True),
        ),
    ]
