# Generated by Django 4.1.1 on 2022-10-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_vessel_lat_alter_vessel_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
